version: '3.8'

services:
  pix-service:
    build: .
    container_name: pix-service
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    # Configurações de logging para não estourar o disco da VPS
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
