version: '3.8'

services:
  pix-service:
    build: .
    container_name: pix-service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    # Aumenta a mem√≥ria compartilhada para evitar crashes do Chromium
    shm_size: '2gb'
